{% set name = "tidypandas" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tidypandas-{{ version }}.tar.gz
  sha256: ccc01a19bc4a8390693dbbd5f431221e1c84ab719a0a6c5f1b4bd7f6c8a9e43f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.8,<4.0
  run:
    - collections-extended >=2.0.2,<3.0.0
    - pandas >=1.0.0,<2.0.0
    - python >=3.6,<4.0

test:
  imports:
    - tidypandas
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://talegari.github.io/tidypandas/
  doc_url: https://talegari.github.io/tidypandas/
  summary: A grammar of data manipulation for pandas inspired by tidyverse
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
